### ISSUE TITLE
Getting runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ierhyna** [benmesander/flip#1]
Hi,
I get `runtime error: invalid memory address or nil pointer dereference` when run the script.
Go version: 1.10.1, I run it locally on my Mac.
Full output is:

```
go run flip.go
startdoc:  0
numdocs:  0
total number of documents  226
startdoc 1
numdocs 225
totalnumdocs 226
numpages 3
startdocpage 1 enddocpage 3
Downloading photo list data page 1 of 3
Downloading photo list data page 2 of 3
Downloading photo list data page 3 of 3
Document metadata 0
Document metadata 10
Document metadata 20
Document metadata 30
Document metadata 40
Document metadata 50
Document metadata 60
Document metadata 70
Document metadata 80
Document metadata 90
Document metadata 100
Document metadata 110
Document metadata 120
Document metadata 130
Document metadata 140
Document metadata 150
Document metadata 160
Document metadata 170
Document metadata 180
Document metadata 190
Document metadata 200
Document metadata 210
Document metadata 220
downloading doc 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1215a24]

goroutine 1 [running]:
main.SavePicture(0xc42029eff0, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420015bc0, 0x5, 0xc420015d70, ...)
	/Users/ierhyna/go/flip.go:233 +0x74
main.SavePictures(0x1, 0xe1, 0xe2)
	/Users/ierhyna/go/flip.go:270 +0x165
main.main()
	/Users/ierhyna/go/flip.go:97 +0x344
exit status 2
```

Any advices how to fix it? Thanks

**Comment by benmesander** [comment]
Hi Irina,
What version of go are you using?
Thanks,Ben

Sent from Yahoo Mail on Android 
 
  On Mon, Apr 16, 2018 at 6:24 AM, Irina Sokolovskaja<notifications@github.com> wrote:   
Hi,
I get runtime error: invalid memory address or nil pointer dereference when run the script.
Full output is:
go run flip.go
startdoc:  0
numdocs:  0
total number of documents  226
startdoc 1
numdocs 225
totalnumdocs 226
numpages 3
startdocpage 1 enddocpage 3
Downloading photo list data page 1 of 3
Downloading photo list data page 2 of 3
Downloading photo list data page 3 of 3
Document metadata 0
Document metadata 10
Document metadata 20
Document metadata 30
Document metadata 40
Document metadata 50
Document metadata 60
Document metadata 70
Document metadata 80
Document metadata 90
Document metadata 100
Document metadata 110
Document metadata 120
Document metadata 130
Document metadata 140
Document metadata 150
Document metadata 160
Document metadata 170
Document metadata 180
Document metadata 190
Document metadata 200
Document metadata 210
Document metadata 220
downloading doc 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1215a24]

goroutine 1 [running]:
main.SavePicture(0xc42029eff0, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420015bc0, 0x5, 0xc420015d70, ...)
	/Users/ierhyna/go/flip.go:233 +0x74
main.SavePictures(0x1, 0xe1, 0xe2)
	/Users/ierhyna/go/flip.go:270 +0x165
main.main()
	/Users/ierhyna/go/flip.go:97 +0x344
exit status 2

Any advices how to fix it? Thanks
